export const students = [
  {
    id: "stu-basic",
    name: "陈同学",
    grade: "高一",
    profileType: "基础薄弱型",
    baseline: "函数概念和符号语言不稳，遇到复合限制条件容易漏条件。",
    goal: "先把定义域、值域和二次函数图像判断流程固定下来。",
    avatarColor: "#0f766e",
  },
  {
    id: "stu-concept",
    name: "林同学",
    grade: "高一",
    profileType: "概念混淆型",
    baseline: "会做部分计算，但容易混淆零点、交点、奇偶性证明等概念表达。",
    goal: "建立概念边界，提升证明和表达规范性。",
    avatarColor: "#2563eb",
  },
  {
    id: "stu-careless",
    name: "余同学",
    grade: "高一",
    profileType: "粗心计算型",
    baseline: "基础方法基本会，但常在配方、因式分解、端点判断中丢分。",
    goal: "通过步骤检查清单减少非知识性失分。",
    avatarColor: "#b45309",
  },
];

export const topics = [
  {
    id: "domain",
    name: "定义域",
    summary: "识别根式、分式、对数、组合函数中的限制条件，并求交集。",
    orderIndex: 1,
  },
  {
    id: "range",
    name: "值域",
    summary: "用配方、图像、区间端点和单调性判断函数取值范围。",
    orderIndex: 2,
  },
  {
    id: "monotonicity",
    name: "单调性",
    summary: "通过图像、对称轴、底数范围和区间限制判断增减性。",
    orderIndex: 3,
  },
  {
    id: "parity",
    name: "奇偶性",
    summary: "先看定义域对称，再比较 f(-x) 与 f(x) 的关系。",
    orderIndex: 4,
  },
  {
    id: "zero",
    name: "零点",
    summary: "把函数零点转化为方程 f(x)=0，并区分零点和交点坐标。",
    orderIndex: 5,
  },
];

export const misconceptions = [
  {
    id: "m-domain-missing",
    topicId: "domain",
    name: "条件遗漏",
    description: "只检查了分式、根式或对数中的一种限制，没有把全部限制条件取交集。",
    remedy: "训练定义域四步清单：根式非负、分母不为0、对数真数大于0、最后求交集。",
    parentGuidance: "家长监督时不要只问答案对不对，可以让孩子先说出本题有几个限制条件。",
    tags: ["定义域", "限制条件", "交集"],
  },
  {
    id: "m-boundary",
    topicId: "domain",
    name: "边界条件错误",
    description: "把 ≥ 写成 >，或把对数真数 >0 写成 ≥0，导致端点误判。",
    remedy: "用端点代入法检查边界，并对比根式和对数的不同限制。",
    parentGuidance: "家长可以提醒孩子把端点单独代回原式，判断是否真的有意义。",
    tags: ["端点", "边界", "定义域"],
  },
  {
    id: "m-range-local",
    topicId: "range",
    name: "局部看式子",
    description: "只看 x^2 或最高次项，没有考虑一次项、区间限制或顶点位置。",
    remedy: "二次函数优先配方，区间题必须同时检查顶点和端点。",
    parentGuidance: "监督时让孩子写出“配方-顶点-端点-比较”四个字，而不是直接报值域。",
    tags: ["值域", "配方", "顶点"],
  },
  {
    id: "m-range-direction",
    topicId: "range",
    name: "开口方向误判",
    description: "开口向下时仍把值域写成向上无界，或忽略最大值。",
    remedy: "画出简单草图，标出开口方向和顶点，再写区间。",
    parentGuidance: "家长可以让孩子先说“最高点还是最低点”，再写值域。",
    tags: ["开口方向", "最大值", "值域"],
  },
  {
    id: "m-mono-opening",
    topicId: "monotonicity",
    name: "开口方向与单调性混淆",
    description: "以为二次项系数为正就全域递增，忽略对称轴左右单调性不同。",
    remedy: "固定判断顺序：配方找对称轴，再分左右区间看增减。",
    parentGuidance: "监督时让孩子必须写出对称轴，没写对称轴不算完成。",
    tags: ["单调性", "二次函数", "对称轴"],
  },
  {
    id: "m-axis",
    topicId: "monotonicity",
    name: "对称轴计算错误",
    description: "套用 x=-b/(2a) 时符号或分母出错。",
    remedy: "标出 a,b,c 后再代公式，最后用配方结果反查。",
    parentGuidance: "家长可让孩子把 a、b、c 圈出来，减少符号失误。",
    tags: ["公式", "对称轴", "计算"],
  },
  {
    id: "m-parity-sample",
    topicId: "parity",
    name: "以点代证",
    description: "只代入 1 和 -1 就判断奇偶性，没有做一般化证明。",
    remedy: "奇偶性证明必须写 f(-x)，单点只能用来找反例，不能用来证明。",
    parentGuidance: "监督时看孩子有没有写 f(-x)，没有写就说明证明不完整。",
    tags: ["奇偶性", "证明", "f(-x)"],
  },
  {
    id: "m-parity-domain",
    topicId: "parity",
    name: "忽略定义域对称",
    description: "只比较表达式，忘记先判断定义域是否关于原点对称。",
    remedy: "奇偶性第一步固定写：定义域是否关于原点对称。",
    parentGuidance: "家长可以问孩子：这个函数的 x 能不能成对出现？",
    tags: ["定义域", "对称", "奇偶性"],
  },
  {
    id: "m-zero-coordinate",
    topicId: "zero",
    name: "零点与交点混淆",
    description: "把零点写成 (a,0) 坐标，概念表达不规范。",
    remedy: "零点写 x 值，交点写坐标；每次答题后检查题目问的是哪一个。",
    parentGuidance: "家长可以让孩子分别说“零点是什么”和“交点是什么”。",
    tags: ["零点", "交点", "表达"],
  },
  {
    id: "m-factor",
    topicId: "zero",
    name: "因式分解错误",
    description: "只检查乘积，没有检查两数和，或漏掉公因式。",
    remedy: "因式分解后必须反乘验证，零点题要把每个因式分别等于0。",
    parentGuidance: "监督时让孩子把分解式反乘回去，确认没有算错。",
    tags: ["因式分解", "方程", "零点"],
  },
];

export const questions = [
  {
    id: "q-domain-1",
    topicId: "domain",
    title: "根式与分式组合定义域",
    prompt: "求函数 f(x)=sqrt(x-1)/(x-3) 的定义域。",
    difficulty: "基础",
    knowledgePoints: ["根式非负", "分母不为0", "条件取交集"],
    correctAnswer: "[1,3) ∪ (3,+∞)",
    commonWrongAnswer: "x≠3",
    misconceptionId: "m-domain-missing",
    followUp: "这个函数里除了分母不能为0，还有没有别的符号会限制 x 的取值？",
    hint: "先看根号里面，再看分母，最后把两个条件合在一起。",
    steps: ["根式要求 x-1≥0，所以 x≥1。", "分母要求 x-3≠0，所以 x≠3。", "两者取交集，定义域为 [1,3) ∪ (3,+∞)。"],
    variant: {
      strategy: "条件换掉并增加对数限制",
      prompt: "求函数 g(x)=sqrt(x-2)/log2(x-1) 的定义域。",
      answer: "(2,+∞)",
      addedKnowledgePoints: ["对数真数大于0", "对数分母不为0"],
      steps: ["sqrt(x-2) 要求 x≥2。", "log2(x-1) 要求 x-1>0 且 log2(x-1)≠0。", "因此 x>1 且 x≠2。再与 x≥2 取交集，得 (2,+∞)。"],
    },
  },
  {
    id: "q-domain-2",
    topicId: "domain",
    title: "对数函数定义域",
    prompt: "求函数 f(x)=log2(x+2) 的定义域。",
    difficulty: "基础",
    knowledgePoints: ["对数真数大于0", "边界判断"],
    correctAnswer: "(-2,+∞)",
    commonWrongAnswer: "x≥-2",
    misconceptionId: "m-boundary",
    followUp: "对数里的真数可以等于0吗？如果 x=-2，log2(0) 有意义吗？",
    hint: "对数真数必须严格大于0。",
    steps: ["对数真数 x+2 必须大于0。", "解得 x>-2。", "定义域为 (-2,+∞)。"],
    variant: {
      strategy: "条件换掉",
      prompt: "求函数 g(x)=log3(2x-1) 的定义域。",
      answer: "(1/2,+∞)",
      addedKnowledgePoints: ["一次不等式"],
      steps: ["对数真数 2x-1>0。", "解得 x>1/2。", "定义域为 (1/2,+∞)。"],
    },
  },
  {
    id: "q-domain-3",
    topicId: "domain",
    title: "分母中的根式",
    prompt: "求函数 f(x)=1/sqrt(x-4) 的定义域。",
    difficulty: "易错",
    knowledgePoints: ["根式非负", "分母不为0", "边界排除"],
    correctAnswer: "(4,+∞)",
    commonWrongAnswer: "x≥4",
    misconceptionId: "m-boundary",
    followUp: "x=4 时根号有意义，但整个分母会变成什么？",
    hint: "分母不能为0，所以根号里面不能只等于0。",
    steps: ["sqrt(x-4) 在分母上。", "根式要求 x-4≥0，但分母还要求 sqrt(x-4)≠0。", "所以 x-4>0，定义域为 (4,+∞)。"],
    variant: {
      strategy: "条件换掉",
      prompt: "求函数 g(x)=1/sqrt(2x-6) 的定义域。",
      answer: "(3,+∞)",
      addedKnowledgePoints: ["一次不等式"],
      steps: ["分母 sqrt(2x-6) 必须有意义且不为0。", "所以 2x-6>0。", "解得 x>3。"],
    },
  },
  {
    id: "q-domain-4",
    topicId: "domain",
    title: "多限制定义域",
    prompt: "求函数 f(x)=sqrt(2x-6)+1/(x-5) 的定义域。",
    difficulty: "综合",
    knowledgePoints: ["根式非负", "分母不为0", "交集"],
    correctAnswer: "[3,5) ∪ (5,+∞)",
    commonWrongAnswer: "x≥3",
    misconceptionId: "m-domain-missing",
    followUp: "如果 x=5，根号部分没问题，但分式部分会不会出问题？",
    hint: "组合函数要分别检查每一部分。",
    steps: ["sqrt(2x-6) 要求 2x-6≥0，即 x≥3。", "1/(x-5) 要求 x≠5。", "所以定义域为 [3,5) ∪ (5,+∞)。"],
    variant: {
      strategy: "增加一个对数知识点",
      prompt: "求函数 g(x)=sqrt(x-1)+1/(x-4)+log2(x) 的定义域。",
      answer: "[1,4) ∪ (4,+∞)",
      addedKnowledgePoints: ["对数真数大于0"],
      steps: ["sqrt(x-1) 要求 x≥1。", "1/(x-4) 要求 x≠4。", "log2(x) 要求 x>0。", "取交集得 [1,4) ∪ (4,+∞)。"],
    },
  },
  {
    id: "q-range-1",
    topicId: "range",
    title: "二次函数配方求值域",
    prompt: "求函数 f(x)=x^2-4x+5 的值域。",
    difficulty: "基础",
    knowledgePoints: ["配方", "顶点", "最小值"],
    correctAnswer: "[1,+∞)",
    commonWrongAnswer: "[5,+∞)",
    misconceptionId: "m-range-local",
    followUp: "这里能只看 x^2 的最小值吗？-4x 会不会改变最低点？",
    hint: "先把二次函数配成顶点式。",
    steps: ["配方：x^2-4x+5=(x-2)^2+1。", "(x-2)^2≥0，所以 f(x)≥1。", "值域为 [1,+∞)。"],
    variant: {
      strategy: "条件换掉",
      prompt: "求函数 g(x)=x^2+6x+10 的值域。",
      answer: "[1,+∞)",
      addedKnowledgePoints: ["配方"],
      steps: ["g(x)=(x+3)^2+1。", "(x+3)^2≥0。", "值域为 [1,+∞)。"],
    },
  },
  {
    id: "q-range-2",
    topicId: "range",
    title: "开口向下二次函数值域",
    prompt: "求函数 f(x)=-(x+1)^2+3 的值域。",
    difficulty: "基础",
    knowledgePoints: ["开口方向", "最大值", "顶点"],
    correctAnswer: "(-∞,3]",
    commonWrongAnswer: "[3,+∞)",
    misconceptionId: "m-range-direction",
    followUp: "这个二次函数前面有负号，图像是向上开口还是向下开口？",
    hint: "开口向下时顶点对应最大值。",
    steps: ["-(x+1)^2≤0。", "所以 f(x)=-(x+1)^2+3≤3。", "值域为 (-∞,3]。"],
    variant: {
      strategy: "条件换掉",
      prompt: "求函数 g(x)=-(x-2)^2+5 的值域。",
      answer: "(-∞,5]",
      addedKnowledgePoints: ["最大值"],
      steps: ["-(x-2)^2≤0。", "所以 g(x)≤5。", "值域为 (-∞,5]。"],
    },
  },
  {
    id: "q-range-3",
    topicId: "range",
    title: "限定区间一次函数值域",
    prompt: "求函数 f(x)=2x+1 在区间 [-1,3] 上的值域。",
    difficulty: "基础",
    knowledgePoints: ["限定区间", "单调性", "端点"],
    correctAnswer: "[-1,7]",
    commonWrongAnswer: "(-∞,+∞)",
    misconceptionId: "m-range-local",
    followUp: "题目给了 x 的区间，函数还能取到所有实数吗？",
    hint: "一次函数递增，直接看区间两端。",
    steps: ["f(x)=2x+1 在 [-1,3] 上递增。", "f(-1)=-1，f(3)=7。", "值域为 [-1,7]。"],
    variant: {
      strategy: "条件换掉",
      prompt: "求函数 g(x)=-3x+2 在区间 [0,4] 上的值域。",
      answer: "[-10,2]",
      addedKnowledgePoints: ["递减函数端点"],
      steps: ["g(x)=-3x+2 在 [0,4] 上递减。", "g(0)=2，g(4)=-10。", "值域为 [-10,2]。"],
    },
  },
  {
    id: "q-range-4",
    topicId: "range",
    title: "区间二次函数值域",
    prompt: "求函数 f(x)=(x-1)^2+2 在区间 [0,3] 上的值域。",
    difficulty: "综合",
    knowledgePoints: ["顶点", "端点", "限定区间"],
    correctAnswer: "[2,6]",
    commonWrongAnswer: "[2,+∞)",
    misconceptionId: "m-range-local",
    followUp: "虽然开口向上，但 x 被限制在 [0,3]，最大值还能无限大吗？",
    hint: "限定区间内既要看顶点，也要看端点。",
    steps: ["顶点 x=1 在区间 [0,3] 内，最小值 f(1)=2。", "端点 f(0)=3，f(3)=6，所以最大值为6。", "值域为 [2,6]。"],
    variant: {
      strategy: "条件换掉并增加端点比较",
      prompt: "求函数 g(x)=(x+2)^2-1 在区间 [-3,1] 上的值域。",
      answer: "[-1,8]",
      addedKnowledgePoints: ["端点比较"],
      steps: ["顶点 x=-2 在 [-3,1] 内，最小值为 -1。", "g(-3)=0，g(1)=8，最大值为8。", "值域为 [-1,8]。"],
    },
  },
  {
    id: "q-mono-1",
    topicId: "monotonicity",
    title: "二次函数单调区间",
    prompt: "判断函数 f(x)=x^2-4x+1 在 (-∞,2] 与 [2,+∞) 上的单调性。",
    difficulty: "基础",
    knowledgePoints: ["配方", "对称轴", "单调区间"],
    correctAnswer: "在 (-∞,2] 上递减，在 [2,+∞) 上递增。",
    commonWrongAnswer: "整个定义域上递增",
    misconceptionId: "m-mono-opening",
    followUp: "二次项系数为正只能说明开口方向，它能直接说明全域递增吗？",
    hint: "先找对称轴 x=2。",
    steps: ["配方 f(x)=(x-2)^2-3。", "对称轴为 x=2，开口向上。", "左侧递减，右侧递增。"],
    variant: {
      strategy: "条件换掉",
      prompt: "判断函数 g(x)=x^2+2x-3 在 (-∞,-1] 与 [-1,+∞) 上的单调性。",
      answer: "在 (-∞,-1] 上递减，在 [-1,+∞) 上递增。",
      addedKnowledgePoints: ["对称轴"],
      steps: ["g(x)=(x+1)^2-4。", "对称轴为 x=-1。", "开口向上，左减右增。"],
    },
  },
  {
    id: "q-mono-2",
    topicId: "monotonicity",
    title: "开口向下单调性",
    prompt: "判断函数 f(x)=-x^2+2x+3 在 (-∞,1] 与 [1,+∞) 上的单调性。",
    difficulty: "易错",
    knowledgePoints: ["开口向下", "对称轴", "单调性"],
    correctAnswer: "在 (-∞,1] 上递增，在 [1,+∞) 上递减。",
    commonWrongAnswer: "在 (-∞,1] 上递减，在 [1,+∞) 上递增",
    misconceptionId: "m-range-direction",
    followUp: "开口向下时，顶点左侧是往上走还是往下走？",
    hint: "画一个开口向下的抛物线草图。",
    steps: ["f(x)=-(x-1)^2+4。", "对称轴为 x=1，开口向下。", "左侧递增，右侧递减。"],
    variant: {
      strategy: "条件换掉",
      prompt: "判断函数 g(x)=-(x+2)^2+1 在 (-∞,-2] 与 [-2,+∞) 上的单调性。",
      answer: "在 (-∞,-2] 上递增，在 [-2,+∞) 上递减。",
      addedKnowledgePoints: ["顶点式"],
      steps: ["对称轴为 x=-2。", "开口向下。", "左增右减。"],
    },
  },
  {
    id: "q-mono-3",
    topicId: "monotonicity",
    title: "一次函数单调性",
    prompt: "判断函数 f(x)=-3x+2 在 R 上的单调性。",
    difficulty: "基础",
    knowledgePoints: ["一次函数", "斜率", "单调性"],
    correctAnswer: "在 R 上单调递减。",
    commonWrongAnswer: "单调递增",
    misconceptionId: "m-axis",
    followUp: "一次函数的系数 -3 是正还是负？斜率为负时图像往哪个方向走？",
    hint: "一次函数 y=kx+b 中，k<0 时递减。",
    steps: ["一次函数的斜率 k=-3。", "k<0，所以函数在 R 上单调递减。"],
    variant: {
      strategy: "条件换掉",
      prompt: "判断函数 g(x)=4x-7 在 R 上的单调性。",
      answer: "在 R 上单调递增。",
      addedKnowledgePoints: ["斜率"],
      steps: ["斜率 k=4>0。", "所以函数在 R 上单调递增。"],
    },
  },
  {
    id: "q-mono-4",
    topicId: "monotonicity",
    title: "限定区间二次函数单调性",
    prompt: "判断函数 f(x)=(x+1)^2 在区间 [-3,1] 上的单调性。",
    difficulty: "综合",
    knowledgePoints: ["限定区间", "对称轴", "分段单调"],
    correctAnswer: "在 [-3,-1] 上递减，在 [-1,1] 上递增。",
    commonWrongAnswer: "在 [-3,1] 上递增",
    misconceptionId: "m-mono-opening",
    followUp: "区间 [-3,1] 是否跨过了对称轴 x=-1？跨过对称轴时能直接说全区间单调吗？",
    hint: "先找对称轴，再看给定区间和对称轴的关系。",
    steps: ["f(x)=(x+1)^2 的对称轴为 x=-1。", "区间 [-3,1] 跨过对称轴。", "因此在 [-3,-1] 上递减，在 [-1,1] 上递增。"],
    variant: {
      strategy: "条件换掉并增加区间判断",
      prompt: "判断函数 g(x)=(x-2)^2 在区间 [0,5] 上的单调性。",
      answer: "在 [0,2] 上递减，在 [2,5] 上递增。",
      addedKnowledgePoints: ["跨对称轴"],
      steps: ["对称轴为 x=2。", "区间 [0,5] 跨过对称轴。", "左侧递减，右侧递增。"],
    },
  },
  {
    id: "q-parity-1",
    topicId: "parity",
    title: "奇函数判断",
    prompt: "判断函数 f(x)=x^3+x 的奇偶性。",
    difficulty: "基础",
    knowledgePoints: ["f(-x)", "奇函数", "定义域对称"],
    correctAnswer: "奇函数",
    commonWrongAnswer: "代入 1 和 -1 后认为证明完成",
    misconceptionId: "m-parity-sample",
    followUp: "代入一组数能证明所有 x 都满足关系吗？",
    hint: "要计算一般形式 f(-x)。",
    steps: ["定义域 R 关于原点对称。", "f(-x)=(-x)^3+(-x)=-x^3-x=-(x^3+x)=-f(x)。", "所以 f(x) 为奇函数。"],
    variant: {
      strategy: "条件换掉",
      prompt: "判断函数 g(x)=x^5-3x 的奇偶性。",
      answer: "奇函数",
      addedKnowledgePoints: ["奇次幂"],
      steps: ["定义域 R 对称。", "g(-x)=-x^5+3x=-(x^5-3x)=-g(x)。", "所以是奇函数。"],
    },
  },
  {
    id: "q-parity-2",
    topicId: "parity",
    title: "偶函数判断",
    prompt: "判断函数 f(x)=x^2+1 的奇偶性。",
    difficulty: "基础",
    knowledgePoints: ["f(-x)", "偶函数"],
    correctAnswer: "偶函数",
    commonWrongAnswer: "非奇非偶",
    misconceptionId: "m-parity-sample",
    followUp: "把 -x 代进去后，结果和 f(x) 是相同还是相反？",
    hint: "(-x)^2=x^2。",
    steps: ["定义域 R 关于原点对称。", "f(-x)=(-x)^2+1=x^2+1=f(x)。", "所以 f(x) 为偶函数。"],
    variant: {
      strategy: "条件换掉",
      prompt: "判断函数 g(x)=x^4-2 的奇偶性。",
      answer: "偶函数",
      addedKnowledgePoints: ["偶次幂"],
      steps: ["定义域 R 对称。", "g(-x)=x^4-2=g(x)。", "所以是偶函数。"],
    },
  },
  {
    id: "q-parity-3",
    topicId: "parity",
    title: "非奇非偶判断",
    prompt: "判断函数 f(x)=x^2+x 的奇偶性。",
    difficulty: "易错",
    knowledgePoints: ["f(-x)", "非奇非偶", "混合项"],
    correctAnswer: "非奇非偶函数",
    commonWrongAnswer: "奇函数",
    misconceptionId: "m-parity-sample",
    followUp: "f(-x) 能等于 f(x) 或 -f(x) 吗？请把两个结果都比较一下。",
    hint: "既要比较 f(x)，也要比较 -f(x)。",
    steps: ["定义域 R 关于原点对称。", "f(-x)=x^2-x。", "它既不等于 f(x)=x^2+x，也不等于 -f(x)=-x^2-x。", "所以非奇非偶。"],
    variant: {
      strategy: "条件换掉",
      prompt: "判断函数 g(x)=x^3+x^2 的奇偶性。",
      answer: "非奇非偶函数",
      addedKnowledgePoints: ["奇偶项混合"],
      steps: ["g(-x)=-x^3+x^2。", "不等于 g(x)，也不等于 -g(x)。", "所以非奇非偶。"],
    },
  },
  {
    id: "q-parity-4",
    topicId: "parity",
    title: "定义域不对称",
    prompt: "判断函数 f(x)=sqrt(x) 的奇偶性。",
    difficulty: "综合",
    knowledgePoints: ["定义域", "原点对称", "奇偶性前提"],
    correctAnswer: "非奇非偶函数",
    commonWrongAnswer: "偶函数",
    misconceptionId: "m-parity-domain",
    followUp: "奇偶性判断前，定义域 [0,+∞) 关于原点对称吗？",
    hint: "定义域不关于原点对称时，不能是奇函数或偶函数。",
    steps: ["f(x)=sqrt(x) 的定义域是 [0,+∞)。", "该定义域不关于原点对称。", "所以函数非奇非偶。"],
    variant: {
      strategy: "条件换掉",
      prompt: "判断函数 g(x)=1/(x-1) 的奇偶性。",
      answer: "非奇非偶函数",
      addedKnowledgePoints: ["定义域不对称"],
      steps: ["定义域为 x≠1。", "该定义域不关于原点对称。", "所以非奇非偶。"],
    },
  },
  {
    id: "q-zero-1",
    topicId: "zero",
    title: "二次函数零点",
    prompt: "函数 f(x)=x^2-5x+6 的零点是什么？",
    difficulty: "基础",
    knowledgePoints: ["因式分解", "零点", "方程"],
    correctAnswer: "x=2 和 x=3",
    commonWrongAnswer: "(2,0) 和 (3,0)",
    misconceptionId: "m-zero-coordinate",
    followUp: "题目问的是零点还是与 x 轴交点？零点应该写 x 值还是坐标？",
    hint: "零点是让 f(x)=0 的 x 的值。",
    steps: ["令 x^2-5x+6=0。", "因式分解得 (x-2)(x-3)=0。", "所以零点为 x=2 和 x=3。"],
    variant: {
      strategy: "条件换掉",
      prompt: "函数 g(x)=x^2-7x+12 的零点是什么？",
      answer: "x=3 和 x=4",
      addedKnowledgePoints: ["因式分解"],
      steps: ["令 x^2-7x+12=0。", "分解为 (x-3)(x-4)=0。", "零点为 x=3 和 x=4。"],
    },
  },
  {
    id: "q-zero-2",
    topicId: "zero",
    title: "无实数零点",
    prompt: "函数 f(x)=x^2+1 有零点吗？",
    difficulty: "易错",
    knowledgePoints: ["零点", "方程无解", "非负性"],
    correctAnswer: "没有实数零点",
    commonWrongAnswer: "x=1",
    misconceptionId: "m-factor",
    followUp: "x^2 的最小值是多少？x^2+1 可能等于0吗？",
    hint: "在实数范围内 x^2≥0。",
    steps: ["令 x^2+1=0，得 x^2=-1。", "实数范围内 x^2 不可能为负数。", "所以没有实数零点。"],
    variant: {
      strategy: "条件换掉",
      prompt: "函数 g(x)=x^2+4 有零点吗？",
      answer: "没有实数零点",
      addedKnowledgePoints: ["非负性"],
      steps: ["x^2≥0。", "所以 x^2+4>0。", "没有实数零点。"],
    },
  },
  {
    id: "q-zero-3",
    topicId: "zero",
    title: "一次函数零点",
    prompt: "函数 f(x)=2x-6 的零点是什么？",
    difficulty: "基础",
    knowledgePoints: ["一次方程", "零点"],
    correctAnswer: "x=3",
    commonWrongAnswer: "(3,0)",
    misconceptionId: "m-zero-coordinate",
    followUp: "如果写成 (3,0)，它表示的是图像上的什么？题目要的是哪个量？",
    hint: "令 f(x)=0，解出 x。",
    steps: ["令 2x-6=0。", "解得 x=3。", "所以零点为 x=3。"],
    variant: {
      strategy: "条件换掉",
      prompt: "函数 g(x)=-4x+8 的零点是什么？",
      answer: "x=2",
      addedKnowledgePoints: ["一次方程"],
      steps: ["令 -4x+8=0。", "解得 x=2。", "零点为 x=2。"],
    },
  },
  {
    id: "q-zero-4",
    topicId: "zero",
    title: "含公因式的零点",
    prompt: "函数 f(x)=x(x+2)(x-1) 的零点是什么？",
    difficulty: "综合",
    knowledgePoints: ["因式为零", "多个零点", "公因式"],
    correctAnswer: "x=-2, x=0, x=1",
    commonWrongAnswer: "x=-2 和 x=1",
    misconceptionId: "m-factor",
    followUp: "除了 x+2 和 x-1，前面的因式 x 也可能等于0吗？",
    hint: "每一个因式都要分别令它等于0。",
    steps: ["令 x(x+2)(x-1)=0。", "分别得 x=0，x=-2，x=1。", "所以零点为 x=-2, x=0, x=1。"],
    variant: {
      strategy: "条件换掉并增加因式",
      prompt: "函数 g(x)=x(x-3)(x+1)(x-2) 的零点是什么？",
      answer: "x=-1, x=0, x=2, x=3",
      addedKnowledgePoints: ["四个因式"],
      steps: ["令每个因式等于0。", "得到 x=0,3,-1,2。", "整理为 x=-1, x=0, x=2, x=3。"],
    },
  },
];
